version: '3'

services:
  carService:
    container_name: carService
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./CarService:/home/node/app
