version: '3'

services:

  api:
    build:
      context: ./SecureService  # Caminho para o Dockerfile da API
    container_name: apisecure
    ports:
      - "443:443"
    depends_on:
      - mongo
    volumes:
      - ./SecureService:/home/node/app  # Ajuste para o caminho do seu código da API

  mongo:
    image: mongo
    container_name: mongodbmicro
    restart: always
    volumes:
      - ./dados_mongo:/data/db
