version: '3'

services:
  userservice:
      container_name: userService
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "443:443"
      volumes:
        - ./UserService:/home/node/app
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./dados_mongo:/data/db