version: '3'

services:
  userService:
      container_name: userService
      build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "443:443"
      volumes:
        - ./UserService:/home/node/app 