version: '3'

services:
  userService:
      container_name: userService
      ports:
        - "443:443"
      volumes:
        - ./UserService:/home/node/app 

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./dados_mongo:/data/db